title: 无人机对地通信场景中3D信道地图构建
description: 我们致力于用数字孪生辅助通信。
site_title: '无人机对地通信场景中3D信道地图构建'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SEU-SRTP
blog_url: https://www.nagekar.com
email: zhaobanbdwp@zohomail.cn
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/IMG_2510.jpg

# Google Analytics ID
google_analytics: 
